### ISSUE TITLE
Add event amplitude to one of the standard output files

### ISSUE THREAD

**Issue by rumachan** [ahotovec/REDPy#19]
In demo'ing some REDpy results to colleagues I mentioned that I thought the events in clusters did not reflect a scale bound process, such as you might see with some earthquakes of volcanic origin. I was asked if I could construct a frequency-magnitude curve to more clearly demonstrate that was a reasonable conclusion. I am wondering if event amplitudes could be added to an appropriate output file, which would make constructing a frequency-magnitude curve for any cluster a trivial matter. Amplitudes are stored and graphed, so I assume outputting wouldn't be too hard. If amplitude was added, would there be an argument for adding other features of cluster events, such as Frequency Index?
Many thanks

**Comment by ahotovec** [comment]
Easy answer here! In the configuration file, just include `verbosecatalog=True` and it will print out additional columns including FI and stored amplitudes on all stations.

**Comment by rumachan** [comment]
I'm sorry, now I feel like a right twit! Thank you very much.

**Comment by ahotovec** [comment]
No worries. My documentation is a little out of date, so the feature isn't as clear as it probably should be.
