### ISSUE TITLE
windowAmp, FI and CCC in catalog.txt

### ISSUE THREAD

**Issue by lvanderlaat** [ahotovec/REDPy#26]
Could you add columns: windowAmp, ccc  and FI to the catalog.txt?

This would be very useful for our monitoring tasks in Costa Rica and Colombia.

I tried to do this myself by loading the h5 file, but had difficulties since I don't have a good knowledge on how the h5 tables are structured. 

Thank you!

**Comment by ahotovec** [comment]
Easy answer here! In your .cfg file, add the following line:

`verbosecatalog=True`

I'm currently preparing a major update to the code as well as much more involved documentation that will make these tasks a lot easier as well. Fingers crossed by end of the year...
