### ISSUE TITLE
Support for Python 3.x?

### ISSUE THREAD

**Issue by echavess** [ahotovec/REDPy#5]
Hi Alicia,
It seems that the code is not supported in python 3.6. Are you planning to extend the support for Python 3.x? 

Thanks!

**Comment by ahotovec** [comment]
Esteban—

It isn't high on the priority list at the moment. If you'd like to try your hand at porting it, by all means! Otherwise, it's going to stay 2.7 for the foreseeable future (basically until the packages it depends on stop supporting 2.7).

**Comment by ahotovec** [comment]
Only a few months after seeing this, I have _finally_ updated the code to support 3.5+!
