### ISSUE TITLE
plotJunk.py error with Windows

### ISSUE THREAD

**Issue by kylebrill** [ahotovec/REDPy#7]
I was getting an error when trying to use plotJunk.py because filenames can't include ':' on Windows. I was able to get it to run fine by just adding a call to `format_fissures`. 

On lines 1094 and 1095 of plotting.py, I changed it from the original:
```
        plt.savefig('{0}/junk/{1}-{2}.png'.format(opt.groupName,
            UTCDateTime(r['startTime'])+opt.ptrig,r['isjunk']), dpi=100)
```
to:
```
        plt.savefig('{0}/junk/{1}-{2}.png'.format(opt.groupName,
            (UTCDateTime(r['startTime'])+opt.ptrig).format_fissures(),r['isjunk']), dpi=100)
```
Not sure if this is the "best" fix or not, but it ran without any errors. 

P.S. Thanks for all your work on this great tool!

**Comment by ahotovec** [comment]
Perfect. I've updated the source code. Thanks for finding an easy fix!
