### ISSUE TITLE
can't open file 'initialize.py'

### ISSUE THREAD

**Issue by fontiela** [ahotovec/REDPy#9]
I installed RedPy via Anaconda (Python2.7) and all dependencies nevertheless, when I run 
`python initialize.py`
I get the following error: 
> can't open file 'initialize.py': [Errno 2] No such file or directory

Additionally, when I do: 
` conda env create -f redpy27.yml`
I obtain this error:
> EnvironmentFileNotFound: '/Users/joaofontiela/redpy27.yml' file not found

My system is MacOS 10.14.6 and anaconda3

Any tips to fix these errors are welcome.

**Comment by ahotovec** [comment]
These commands need to be executed in the folder where the package was downloaded. For example, mine is /Users/ahotovecellis/REDPy/. Make sure you `cd` to the `REDPy` folder and try again.

**Comment by fontiela** [comment]
Thank you for your fast reply.

I tried run initialize.py from the folder where REDpy is installed and I get following error:

> (redpy) MacBook-Pro-de-Joao:redpy joaofontiela$ python initialize.py 
> Traceback (most recent call last):
> File "initialize.py", line 5, in <module>
>            import redpy.config
> ImportError: No module named redpy.config

Then I run again initialize.py with -v option and the message I obtained was: 

(redpy) bash-3.2$ python -v initialize.py 
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/site.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/site.py
import site # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/site.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/os.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/os.py
import os # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/posixpath.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/posixpath.py
import posixpath # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/posixpath.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/stat.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/stat.py
import stat # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/stat.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/genericpath.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/genericpath.py
import genericpath # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/genericpath.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/warnings.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/warnings.py
import warnings # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/warnings.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/linecache.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/linecache.py
import linecache # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/linecache.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/types.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/types.py
import types # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/types.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/UserDict.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/UserDict.py
import UserDict # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/UserDict.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_abcoll.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_abcoll.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/abc.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/abc.py
import abc # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/abc.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_weakrefset.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/copy_reg.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/copy_reg.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/traceback.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/traceback.py
import traceback # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/traceback.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sysconfig.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sysconfig.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/re.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/re.py
import re # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/re.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_compile.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_parse.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_parse.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_constants.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_constants.pyc
dlopen("/Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/lib-dynload/_locale.so", 2);
import _locale # dynamically loaded from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/lib-dynload/_locale.so
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_sysconfigdata.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_sysconfigdata.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_osx_support.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_osx_support.py
import _osx_support # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_osx_support.pyc
import encodings # directory /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/__init__.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/__init__.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/codecs.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/codecs.py
import codecs # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/codecs.pyc
import _codecs # builtin
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/aliases.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/aliases.pyc
# /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/utf_8.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/utf_8.pyc
Python 2.7.15 | packaged by conda-forge | (default, Jul  2 2019, 00:42:22) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "initialize.py", line 5, in <module>
    import redpy.config
ImportError: No module named redpy.config
# clear __builtin__._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.exitfunc
# clear sys.exc_type
# clear sys.exc_value
# clear sys.exc_traceback
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup __main__
# cleanup[1] encodings
# cleanup[1] site
# cleanup[1] sysconfig
# cleanup[1] abc
# cleanup[1] _weakrefset
# cleanup[1] sre_constants
# cleanup[1] _codecs
# cleanup[1] _warnings
# cleanup[1] zipimport
# cleanup[1] _sysconfigdata
# cleanup[1] mpl_toolkits
# cleanup[1] encodings.utf_8
# cleanup[1] _osx_support
# cleanup[1] codecs
# cleanup[1] signal
# cleanup[1] traceback
# cleanup[1] posix
# cleanup[1] encodings.aliases
# cleanup[1] exceptions
# cleanup[1] _weakref
# cleanup[1] re
# cleanup[1] _locale
# cleanup[1] sre_compile
# cleanup[1] _sre
# cleanup[1] sre_parse
# cleanup[2] copy_reg
# cleanup[2] posixpath
# cleanup[2] errno
# cleanup[2] _abcoll
# cleanup[2] types
# cleanup[2] genericpath
# cleanup[2] stat
# cleanup[2] warnings
# cleanup[2] UserDict
# cleanup[2] os.path
# cleanup[2] linecache
# cleanup[2] os
# cleanup sys
# cleanup __builtin__
# cleanup ints: 20 unfreed ints
# cleanup floats

I noticed that I don't have  `settings.cfg` file.
I installed REDpy (python2.7) with Anaconda.

**Comment by fontiela** [comment]
Thank you for your fast reply.

I tried run initialize.py from the folder where REDpy is installed and I get following error:

> (redpy) MacBook-Pro-de-Joao:redpy joaofontiela$ python initialize.py 
> Traceback (most recent call last):
> File "initialize.py", line 5, in <module>
>            import redpy.config
> ImportError: No module named redpy.config

Then I run again initialize.py with -v option and the message I obtained was: 

> (redpy) bash-3.2$ python -v initialize.py 
> # installing zipimport hook
> import zipimport # builtin
> # installed zipimport hook
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/site.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/site.py
> import site # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/site.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/os.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/os.py
> import os # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/os.pyc
> import errno # builtin
> import posix # builtin
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/posixpath.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/posixpath.py
> import posixpath # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/posixpath.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/stat.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/stat.py
> import stat # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/stat.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/genericpath.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/genericpath.py
> import genericpath # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/genericpath.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/warnings.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/warnings.py
> import warnings # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/warnings.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/linecache.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/linecache.py
> import linecache # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/linecache.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/types.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/types.py
> import types # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/types.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/UserDict.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/UserDict.py
> import UserDict # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/UserDict.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_abcoll.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_abcoll.py
> import _abcoll # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_abcoll.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/abc.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/abc.py
> import abc # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/abc.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_weakrefset.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_weakrefset.py
> import _weakrefset # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_weakrefset.pyc
> import _weakref # builtin
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/copy_reg.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/copy_reg.py
> import copy_reg # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/copy_reg.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/traceback.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/traceback.py
> import traceback # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/traceback.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sysconfig.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sysconfig.py
> import sysconfig # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sysconfig.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/re.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/re.py
> import re # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/re.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_compile.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_compile.py
> import sre_compile # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_compile.pyc
> import _sre # builtin
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_parse.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_parse.py
> import sre_parse # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_parse.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_constants.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_constants.py
> import sre_constants # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/sre_constants.pyc
> dlopen("/Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/lib-dynload/_locale.so", 2);
> import _locale # dynamically loaded from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/lib-dynload/_locale.so
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_sysconfigdata.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_sysconfigdata.py
> import _sysconfigdata # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_sysconfigdata.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_osx_support.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_osx_support.py
> import _osx_support # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/_osx_support.pyc
> import encodings # directory /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/__init__.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/__init__.py
> import encodings # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/__init__.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/codecs.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/codecs.py
> import codecs # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/codecs.pyc
> import _codecs # builtin
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/aliases.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/aliases.py
> import encodings.aliases # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/aliases.pyc
> # /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/utf_8.pyc matches /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/utf_8.py
> import encodings.utf_8 # precompiled from /Users/joaofontiela/anaconda3/envs/redpy/lib/python2.7/encodings/utf_8.pyc
> Python 2.7.15 | packaged by conda-forge | (default, Jul  2 2019, 00:42:22) 
> [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> Traceback (most recent call last):
>   File "initialize.py", line 5, in <module>
>     import redpy.config
> ImportError: No module named redpy.config
> # clear __builtin__._
> # clear sys.path
> # clear sys.argv
> # clear sys.ps1
> # clear sys.ps2
> # clear sys.exitfunc
> # clear sys.exc_type
> # clear sys.exc_value
> # clear sys.exc_traceback
> # clear sys.last_type
> # clear sys.last_value
> # clear sys.last_traceback
> # clear sys.path_hooks
> # clear sys.path_importer_cache
> # clear sys.meta_path
> # clear sys.flags
> # clear sys.float_info
> # restore sys.stdin
> # restore sys.stdout
> # restore sys.stderr
> # cleanup __main__
> # cleanup[1] encodings
> # cleanup[1] site
> # cleanup[1] sysconfig
> # cleanup[1] abc
> # cleanup[1] _weakrefset
> # cleanup[1] sre_constants
> # cleanup[1] _codecs
> # cleanup[1] _warnings
> # cleanup[1] zipimport
> # cleanup[1] _sysconfigdata
> # cleanup[1] mpl_toolkits
> # cleanup[1] encodings.utf_8
> # cleanup[1] _osx_support
> # cleanup[1] codecs
> # cleanup[1] signal
> # cleanup[1] traceback
> # cleanup[1] posix
> # cleanup[1] encodings.aliases
> # cleanup[1] exceptions
> # cleanup[1] _weakref
> # cleanup[1] re
> # cleanup[1] _locale
> # cleanup[1] sre_compile
> # cleanup[1] _sre
> # cleanup[1] sre_parse
> # cleanup[2] copy_reg
> # cleanup[2] posixpath
> # cleanup[2] errno
> # cleanup[2] _abcoll
> # cleanup[2] types
> # cleanup[2] genericpath
> # cleanup[2] stat
> # cleanup[2] warnings
> # cleanup[2] UserDict
> # cleanup[2] os.path
> # cleanup[2] linecache
> # cleanup[2] os
> # cleanup sys
> # cleanup __builtin__
> # cleanup ints: 20 unfreed ints
> # cleanup floats

I noticed that I don't have  `settings.cfg` file.
I installed REDpy (python2.7) with Anaconda.

**Comment by ahotovec** [comment]
Can you list the contents of the folder you are in? And of `redpy/` within it. I want to make sure everything that should be there is there!

**Comment by fontiela** [comment]
The content of `redpy/` folder is

bin
conda-meta
etc
include
initialize.py
lib
libexec
man
redpy27.yml
share
ssl

And redpy  is installed `/Users/joaofontiela/anaconda3/envs/redpy`

**Comment by ahotovec** [comment]
Download the contents of this zip file ([https://github.com/ahotovec/REDPy/archive/master.zip](https://github.com/ahotovec/REDPy/archive/master.zip)) or use git to clone a copy of the entire repository ([https://github.com/ahotovec/REDPy.git](https://github.com/ahotovec/REDPy.git)) to a working folder (e.g., `/Users/joaofontiela/REDPy/`) and run the scripts from there.

**Comment by fontiela** [comment]
I run test file  and it's working perfectly.
Thank you very much for your help.

**Comment by ahotovec** [comment]
Great. I realize now in re-reading the installation instructions that there is no explicit 'download the repository to a working directory' first before installing dependencies. I'll add that for more clarity in installation going forward. Feel free to follow up with me via email if you have further issues setting up a custom run.
